#!/usr/bin/env bash
# Instalar el servidor web nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html 
sudo service nginx start
