#!/usr/bin/env bash
# Instalar el servidor web nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo chmod -R 777 /etc/nginx
sed -i "/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
