#!/usr/bin/env bash
# Instalar el servidor web nginx
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo service nginx start
sudo chmod -R 777 /etc/nginx
sed -i "/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
sudo touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i '35 a \ \t error_page 404 /custom_404.html; \n\t location = /custom_404.html { \n\t\t root /usr/share/nginx/html; \n\t\t internal; \n\t}' /etc/nginx/sites-available/default
sed -i '14 a \\tadd_header X-Served-By \$HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx restart
