#!/usr/bin/env bash
#Install and configure HAproxy 
sudo apt-get update -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get install haproxy -y
sudo chmod 777 /etc/haproxy/
sed -i "$ a frontend firstbalance \n\tbind *:80 \n\tmode http \n\tdefault_backend webservers" /etc/haproxy/haproxy.cfg
sed -i "$ a backend webservers \n\tbalance roundrobin \n\tmode http \n\tserver 1166-web-01 104.196.117.221:80 check \n\tserver 1166-web-02 54.221.125.45:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart

