#!/usr/bin/env bash
# listen port 80
sed -i 's/8080 default_server;/80 default_server;/g' /etc/nginx/sites-enabled/default
sed -i 's/8080 default_server ipv6only=on;/80 default_server;/g' /etc/nginx/sites-enabled/default
sudo service nginx restart

