#!/usr/bin/env bash
# This script is display informtation about /etc/passwd file.
file=/etc/passwd
IFS=':'
while read -r name password user_ID group_ID gecos home_directory shell
do
	printf "The user %s is part of the %s gang, lives in %s and rides %s." "$name" "$group_ID" "$home_directory" "$shell"
	printf " %s's place is protected by the passcode %s, more info about the user here: %s\n" "$user_ID" "$password" "$gecos"

#printf "%s:%s:%s:%s:%s:%s:%s\n" $name $password $user_ID $group_ID $gecos $home_directory $shell
done < "$file"
